### ISSUE TITLE
Unpredictable histogram saving behaviour

### ISSUE THREAD

**Issue by durga2112** [Astroua/CARTAvis#96]
When saving a histogram, I have noticed that the resulting image depends a little too heavily upon what is currently shown in the application window. Try the following sequence of steps:

- save a histogram with the Aspect Ratio set to Ignore and the size set to 400x500
- change the size of the histogram window (e.g. by resizing the widgets in the application or by resizing the window) and save the histogram again, preferably with a different image name, and with the Ignore and 400x500 settings as before
- view the resulting images

When I do this, the images I get are 400x500, as expected, but the actual content of the images differs, which I would not expect; I would expect the resulting images to be identical. Here are three images produced by saving the histogram with the same image settings but with different sized histogram windows:

![image](https://cloud.githubusercontent.com/assets/4204212/10642185/88c32950-77ea-11e5-9d81-fac02770e16d.png)

![image](https://cloud.githubusercontent.com/assets/4204212/10642196/92239908-77ea-11e5-9191-10636d42aa1d.png)

![image](https://cloud.githubusercontent.com/assets/4204212/10642206/995038e4-77ea-11e5-9afd-6fc5fc3bc7d2.png)

**Comment by pfederl** [comment]
I uploaded a fix in my PavolHotfix branch: 731431d1606b97e1444743db2ff2678a4131022c

I believe the problem was caused by this line in ImageRenderService.h:

    void
    setInputView( NdArray::RawViewInterface::SharedPtr view, QString cacheId = QString(), int displayAxisX = 0, int displayAxisY= 0 );

Those are invalid default parameters, and since in ImageSaveService you don't set them, it creates all kinds of chaos for non-square images... It should be instead:

    void
    setInputView( NdArray::RawViewInterface::SharedPtr view, QString cacheId = QString(), int displayAxisX = 0, int displayAxisY= 1 );

On a related note, in ImageRenderService.cpp:

    template < class Pipeline >
    static void
    iView2qImage( NdArray::RawViewInterface * rawView, Pipeline & pipe, QImage & qImage, int displayAxisX, int displayAxisY )

this internal function will ONLY work with displayAxisX/Y set to 0,1 respectively. It will not work for any other values, and most likely lead to memory corruption. So I put in a fatal crash if someone tries to use it with values other than 0,1.

On yet another related subject... Your save image functionality behaves quite oddly once you actually interactively set the zoom level to something less than 1. At some point QImage of size 0x0 is created, which makes it impossible to paint to it, etc. I left in some debug statements that should allow you to debug it easier. The code will generate quite a few warning messages too.

**Comment by slovelan** [comment]
The problem appears to be in your saveHistogram method.  The default 
"scaled"
method of the QImage class is to use a "Qt::FastTransformation". This 
appears to
skip details such as some histogram lines.  When I changed to a 
"Qt::SmoothTransformation"
the problem disappears.  I have committed a fix for this that will be 
available in
my next pull request.

**Comment by durga2112** [comment]
@pfederl: would you like me to work on the save image bug you mentioned? Is the pavolHotfix branch something I should be able to grab and work with, or would it be better to wait until it is merged into develop?

**Comment by slovelan** [comment]
The code that Pavol fixed was removed from my code base when I put in 
the code for
permuting an image.  That is why I could not reproduce the problem.   
Thus, I would
recommend not working with it as it is old code.

**Comment by pfederl** [comment]
I merged in my pull request so you can continue debugging the related zoom
issue & saving.

On Fri, Oct 23, 2015 at 1:44 PM, Jeff Taylor <notifications@github.com>
wrote:

> @pfederl <https://github.com/pfederl>: would you like me to work on the
> save image bug you mentioned? Is the pavolHotfix branch something I should
> be able to grab and work with, or would it be better to wait until it is
> merged into develop?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Astroua/CARTAvis/issues/96#issuecomment-150672789>.
>



-- 
Pavol

**Comment by pfederl** [comment]
Susan, are your changes ready for pull request?

On Fri, Oct 23, 2015 at 1:59 PM, slovelan <notifications@github.com> wrote:

> The code that Pavol fixed was removed from my code base when I put in
> the code for
> permuting an image. That is why I could not reproduce the problem.
> Thus, I would
> recommend not working with it as it is old code.
>
> On 10/23/2015 01:44 PM, Jeff Taylor wrote:
> >
> > @pfederl <https://github.com/pfederl>: would you like me to work on
> > the save image bug you mentioned? Is the pavolHotfix branch something
> > I should be able to grab and work with, or would it be better to wait
> > until it is merged into develop?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/Astroua/CARTAvis/issues/96#issuecomment-150672789>.Web
>
> > Bug from
> >
> https://github.com/notifications/beacon/AGSu-_ecYnkTeLz7YQGLWbolRRPGQNgyks5o-oW2gaJpZM4GTGCE.gif
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Astroua/CARTAvis/issues/96#issuecomment-150675613>.
>



-- 
Pavol

**Comment by slovelan** [comment]
I'm sorry, they are not.  I know that I need to get them in, but I left 
the axis work in an unstable
state.  At the beginning of  the week I could not work on CARTA because 
I had two plus days of
CASA work to do.  Then in the later part of this week, I have been 
getting distracted by all of
Jeff's bugs, thinking I should address them rather than having other 
people spend time on them.
I will try to stabilize the axis work as soon as I can.  A lot depends 
on how hard it is to find a solution
to the axis problem I need to address, but maybe I can do a pull request 
sometime this weekend
or early next week.

**Comment by pfederl** [comment]
No problem Susan, I just wanted to know if I should be looking out for a
pull request needing to be merged in over the weekend. My work definitely
does not depend on it, and I think Jeff can probably continue working with
the hotfix I just uploaded.


On Fri, Oct 23, 2015 at 3:11 PM, slovelan <notifications@github.com> wrote:

> I'm sorry, they are not. I know that I need to get them in, but I left
> the axis work in an unstable
> state. At the beginning of the week I could not work on CARTA because
> I had two plus days of
> CASA work to do. Then in the later part of this week, I have been
> getting distracted by all of
> Jeff's bugs, thinking I should address them rather than having other
> people spend time on them.
> I will try to stabilize the axis work as soon as I can. A lot depends
> on how hard it is to find a solution
> to the axis problem I need to address, but maybe I can do a pull request
> sometime this weekend
> or early next week.
>
> On 10/23/2015 03:04 PM, Pavol Federl wrote:
> > Susan, are your changes ready for pull request?
> >
> > On Fri, Oct 23, 2015 at 1:59 PM, slovelan <notifications@github.com>
> > wrote:
> >
> > > The code that Pavol fixed was removed from my code base when I put in
> > > the code for
> > > permuting an image. That is why I could not reproduce the problem.
> > > Thus, I would
> > > recommend not working with it as it is old code.
> > >
> > > On 10/23/2015 01:44 PM, Jeff Taylor wrote:
> > > >
> > > > @pfederl <https://github.com/pfederl>: would you like me to work on
> > > > the save image bug you mentioned? Is the pavolHotfix branch something
> > > > I should be able to grab and work with, or would it be better to wait
> > > > until it is merged into develop?
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > >
> > <https://github.com/Astroua/CARTAvis/issues/96#issuecomment-150672789
> >.Web
> > >
> > > > Bug from
> > > >
> > >
> >
> https://github.com/notifications/beacon/AGSu-_ecYnkTeLz7YQGLWbolRRPGQNgyks5o-oW2gaJpZM4GTGCE.gif
> > >
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/Astroua/CARTAvis/issues/96#issuecomment-150675613
> >.
> > >
> >
> >
> >
> > --
> > Pavol
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/Astroua/CARTAvis/issues/96#issuecomment-150692298>.Web
>
> > Bug from
> >
> https://github.com/notifications/beacon/AGSu-6yDbxuVe5yiMls_leR8K8pZtxmdks5o-phJgaJpZM4GTGCE.gif
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Astroua/CARTAvis/issues/96#issuecomment-150693704>.
>



-- 
Pavol

**Comment by slovelan** [comment]
Yes.  Just a note to Jeff, don't spend effort on getting the two 
additional parameters for
setting the display axes to work in the method where there was a bad 
default parameter.  Both of
those parameters will be gone when I check in.

**Comment by durga2112** [comment]
Pavol, I just checked out your code and it does not seem to fix issue #96. Do I have this right: the actual fix for #96 will come from Susan, and your recent pull request was made so that I can debug the zoom issue?

**Comment by slovelan** [comment]
Pavol accidentally reported that he had fixed issue #96, when he instead 
fixed the crash you
were getting for some images.  Issue #96 will be fixed when I check in 
my code.

**Comment by durga2112** [comment]
Excellent, thanks for the clarification!

**Comment by pfederl** [comment]
Oops. Susan is right. I fixed your crashing code that's all. Was there an
open issue for that?

**Comment by pfederl** [comment]
I copied my comment to the appropriate issue #94.

On Fri, Oct 23, 2015 at 7:32 PM, Pavol Federl <federl@gmail.com> wrote:

> Oops. Susan is right. I fixed your crashing code that's all. Was there an
> open issue for that?
> On Oct 23, 2015 4:24 PM, "Jeff Taylor" <notifications@github.com> wrote:
>
>> Excellent, thanks for the clarification!
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/Astroua/CARTAvis/issues/96#issuecomment-150706487>.
>>
>


-- 
Pavol

**Comment by durga2112** [comment]
This issue still doesn't look fixed to me after merging #99. Here are two images that were saved using the same parameters, before and after changing the size of the histogram window. They look better than they did before, but they are still clearly not identical. Is this a bug, or is my expectation of identical images not realistic?

![hist2](https://cloud.githubusercontent.com/assets/4204212/10830319/6aeddc9c-7e55-11e5-8e2d-b95b37ca2a82.png)
![hist1](https://cloud.githubusercontent.com/assets/4204212/10830320/6aef2e12-7e55-11e5-9599-f2b1a3c02eab.png)

**Comment by slovelan** [comment]
When the images of different sizes will be scaled differently when they 
are saved to the same size.

**Comment by slovelan** [comment]
Apparently, when you wrote the save histogram method, you did not intend to actually scale the image with Qt::IgnoreAspectRatio since images of different sizes will be scaled differently to the same size.  I have taken a second pass at rewriting your method so that it does not perform scaling for Qt::IgnoreAspectRatio, which is what I think you must have intended when you wrote the method.  This will be in my next check-in.
